# /oak:
#   ros__parameters:
#     camera:
#       i_enable_imu: true
#       i_enable_ir: false
#       i_pipeline_type: depth
#       i_publish_tf_from_calibration: true
#     stereo:
#       i_publish_topic: false
#       i_reverse_stereo_socket_order: true
#       i_publish_synced_rect_pair: true
#       i_update_ros_base_time_on_ros_msg: true
#     left:
#       i_resolution: '400'
#       i_fps: 30.0
#     right:
#       i_resolution: '400'
#       i_fps: 30.0

/oak:
  ros__parameters:
    camera:
      i_calibration_dump: true
      i_enable_imu: true
      i_enable_ir: false
      i_pipeline_type: RGBD
      i_publish_tf_from_calibration: true
      i_tf_imu_from_descr: 'true'
      i_usb_speed: SUPER_PLUS
      i_nn_type: none
    stereo:
      i_publish_topic: true
      i_reverse_stereo_socket_order: true
      i_publish_synced_rect_pair: true
      i_update_ros_base_time_on_ros_msg: false
      i_align_depth: true
      i_resolution: '720P'
      i_left_rect_low_bandwidth: true
      i_left_rect_low_bandwidth_quality: 50
      i_right_rect_low_bandwidth: true
      i_right_rect_low_bandwidth_quality: 50
      i_low_bandwidth: true
      i_low_bandwidth_quality: 50
    imu:
      i_acc_cov: 0.0
      i_acc_freq: 100
      i_batch_report_threshold: 5
      i_enable_rotation: false
      i_get_base_device_timestamp: false
      i_gyro_cov: 0.0
      i_gyro_freq: 100
      i_mag_cov: 0.0
      i_max_batch_reports: 10
      i_message_type: IMU
      i_rot_cov: 0.0
      i_rot_freq: 0
      i_sync_method: LINEAR_INTERPOLATE_ACCEL
      i_update_ros_base_time_on_ros_msg: false
    left:
      i_resolution: '400P'
      i_fps: 60.0
      i_low_bandwidth: true
      i_low_bandwidth_quality: 50
    right:
      i_resolution: '400P'
      i_fps: 60.0
      i_low_bandwidth: true
      i_low_bandwidth_quality: 50
    rgb:
      i_resolution: '1080P'
      i_isp_den: 3
      i_isp_num: 2
      i_output_isp: true
      i_fps: 30.0
      i_low_bandwidth: true
      i_low_bandwidth_quality: 50
      i_publish_topic: true
    use_sim_time: false

# /oak:
#   ros__parameters:
#     camera:
#       i_calibration_dump: true
#       i_enable_imu: true
#       i_enable_ir: true
#       i_pipeline_type: RGBD
#       i_publish_tf_from_calibration: true
#       i_tf_imu_from_descr: 'true'
#       i_usb_speed: SUPER_PLUS
#       i_nn_type: none
#     stereo:
#       i_publish_topic: true
#       i_reverse_stereo_socket_order: true
#       i_publish_synced_rect_pair: true
#       i_publish_left_rect: true
#       i_publish_right_rect: true
#       i_update_ros_base_time_on_ros_msg: false
#       i_align_depth: true
#       i_resolution: '400P'
#       i_low_bandwidth: true
#       i_low_bandwidth_quality: 10
#     left:
#       i_height: 400
#       i_width: 640
#       i_fps: 117.0
#       i_low_bandwidth: true
#       i_low_bandwidth_quality: 10
#     right:
#       i_height: 400
#       i_width: 640
#       i_fps: 117.0
#       i_low_bandwidth: true
#       i_low_bandwidth_quality: 10
#     rgb:
#       i_resolution: '1080P'
#       i_isp_den: 3
#       i_isp_num: 2
#       i_output_isp: true
#       i_fps: 30.0
#       i_low_bandwidth: true
#       i_low_bandwidth_quality: 10
#       i_publish_topic: true
#     use_sim_time: false

# /oak:
#   ros__parameters:
#     camera:
#       i_calibration_dump: false
#       i_enable_imu: true
#       i_enable_ir: true
#       i_external_calibration_path: ''
#       i_floodlight_brightness: 0
#       i_ip: ''
#       i_laser_dot_brightness: 500
#       i_mx_id: ''
#       i_nn_type: none
#       i_pipeline_dump: false
#       i_pipeline_type: RGBD
#       i_publish_tf_from_calibration: true
#       i_tf_base_frame: oak
#       i_tf_cam_pitch: '0.0'
#       i_tf_cam_pos_x: '0.0'
#       i_tf_cam_pos_y: '0.0'
#       i_tf_cam_pos_z: '0.0'
#       i_tf_cam_roll: '0.0'
#       i_tf_cam_yaw: '0.0'
#       i_tf_camera_model: ''
#       i_tf_camera_name: oak
#       i_tf_custom_urdf_location: ''
#       i_tf_custom_xacro_args: ''
#       i_tf_imu_from_descr: 'true'
#       i_tf_parent_frame: oak-d-base-frame
#       i_usb_port_id: ''
#       i_usb_speed: SUPER_PLUS
#     diagnostic_updater:
#       period: 1.0
#     imu:
#       i_acc_cov: 0.0
#       i_acc_freq: 250
#       i_batch_report_threshold: 5
#       i_enable_rotation: true
#       i_get_base_device_timestamp: false
#       i_gyro_cov: 0.0
#       i_gyro_freq: 200
#       i_mag_cov: 0.0
#       i_max_batch_reports: 10
#       i_message_type: IMU
#       i_rot_cov: 0.0
#       i_rot_freq: 200
#       i_sync_method: LINEAR_INTERPOLATE_ACCEL
#       i_update_ros_base_time_on_ros_msg: false
#     left:
#       i_add_exposure_offset: false
#       i_board_socket_id: 1
#       i_calibration_file: 'package://depthai_ros_driver/config/calibration/left_640x400.yaml'
#       i_disable_node: false
#       i_enable_feature_tracker: false
#       i_enable_lazy_publisher: true
#       i_exposure_offset: 0
#       i_fps: 30.0
#       i_fsync_continuous: false
#       i_fsync_trigger: false
#       i_get_base_device_timestamp: false
#       i_low_bandwidth: false
#       i_low_bandwidth_quality: 50
#       i_max_q_size: 30
#       i_publish_topic: true
#       i_resolution: 400P
#       i_reverse_stereo_socket_order: false
#       i_sensor_img_orientation: NORMAL
#       i_set_isp3a_fps: false
#       i_simulate_from_topic: false
#       i_simulated_topic_name: ''
#       i_update_ros_base_time_on_ros_msg: false
#       r_exposure: 1000
#       r_iso: 800
#       r_set_man_exposure: false
#     nn:
#       i_disable_resize: false
#       i_enable_passthrough: false
#       i_enable_passthrough_depth: false
#       i_get_base_device_timestamp: false
#       i_num_inference_threads: 2
#       i_num_pool_frames: 4
#       i_update_ros_base_time_on_ros_msg: false
#     rgb:
#       i_add_exposure_offset: false
#       i_board_socket_id: 0
#       i_calibration_file: 'package://depthai_ros_driver/config/calibration/rgb_1040x780.yaml'
#       i_disable_node: false
#       i_enable_feature_tracker: false
#       i_enable_lazy_publisher: true
#       i_enable_preview: false
#       i_exposure_offset: 0
#       i_fps: 30.0
#       i_fsync_continuous: false
#       i_fsync_trigger: false
#       i_get_base_device_timestamp: false
#       i_height: 720
#       i_interleaved: false
#       i_isp_den: 39
#       i_isp_num: 10
#       i_output_isp: true
#       i_keep_preview_aspect_ratio: true
#       i_low_bandwidth: false
#       i_low_bandwidth_quality: 50
#       i_max_q_size: 30
#       i_preview_height: 300
#       i_preview_size: 300
#       i_preview_width: 300
#       i_publish_topic: true
#       i_resolution: 12MP
#       i_reverse_stereo_socket_order: false
#       i_sensor_img_orientation: NORMAL
#       i_set_isp3a_fps: false
#       i_set_isp_scale: true
#       i_simulate_from_topic: false
#       i_simulated_topic_name: ''
#       i_update_ros_base_time_on_ros_msg: false
#       i_width: 1280
#       r_exposure: 20000
#       r_focus: 1
#       r_iso: 800
#       r_set_man_exposure: false
#       r_set_man_focus: false
#       r_set_man_whitebalance: false
#       r_whitebalance: 3300
#     right:
#       i_add_exposure_offset: false
#       i_board_socket_id: 2
#       i_calibration_file: 'package://depthai_ros_driver/config/calibration/right_640x400.yaml'
#       i_disable_node: false
#       i_enable_feature_tracker: false
#       i_enable_lazy_publisher: true
#       i_exposure_offset: 0
#       i_fps: 30.0
#       i_fsync_continuous: false
#       i_fsync_trigger: false
#       i_get_base_device_timestamp: false
#       i_low_bandwidth: false
#       i_low_bandwidth_quality: 50
#       i_max_q_size: 30
#       i_publish_topic: true
#       i_resolution: 400P
#       i_reverse_stereo_socket_order: false
#       i_sensor_img_orientation: NORMAL
#       i_set_isp3a_fps: false
#       i_simulate_from_topic: false
#       i_simulated_topic_name: ''
#       i_update_ros_base_time_on_ros_msg: false
#       r_exposure: 1000
#       r_iso: 800
#       r_set_man_exposure: false
#     stereo:
#       i_add_exposure_offset: false
#       i_align_depth: true
#       i_bilateral_sigma: 0
#       i_board_socket_id: 0
#       i_decimation_filter_decimation_factor: 2
#       i_decimation_filter_decimation_mode: NON_ZERO_MEAN
#       i_depth_filter_size: 7
#       i_depth_preset: HIGH_ACCURACY
#       i_disparity_width: DISPARITY_96
#       i_enable_alpha_scaling: false
#       i_enable_brightness_filter: true
#       i_enable_companding: false
#       i_enable_decimation_filter: false
#       i_enable_disparity_shift: false
#       i_enable_distortion_correction: false
#       i_enable_lazy_publisher: true
#       i_enable_spatial_filter: false
#       i_enable_speckle_filter: true
#       i_enable_temporal_filter: false
#       i_enable_threshold_filter: true
#       i_exposure_offset: 0
#       i_extended_disp: true
#       i_get_base_device_timestamp: false
#       i_height: 780
#       i_left_rect_add_exposure_offset: false
#       i_left_rect_enable_feature_tracker: false
#       i_left_rect_exposure_offset: 0
#       i_left_rect_low_bandwidth: false
#       i_left_rect_low_bandwidth_quality: 50
#       i_left_socket_id: 1
#       i_low_bandwidth: false
#       i_low_bandwidth_quality: 50
#       i_lr_check: true
#       i_lrc_threshold: 10
#       i_max_q_size: 30
#       i_output_disparity: false
#       i_publish_left_rect: true
#       i_publish_right_rect: true
#       i_publish_synced_rect_pair: true
#       i_publish_topic: true
#       i_rectify_edge_fill_color: 0
#       i_reverse_stereo_socket_order: false
#       i_right_rect_add_exposure_offset: false
#       i_right_rect_enable_feature_tracker: false
#       i_right_rect_exposure_offset: 0
#       i_right_rect_low_bandwidth: false
#       i_right_rect_low_bandwidth_quality: 50
#       i_right_socket_id: 2
#       i_set_input_size: false
#       i_socket_name: rgb
#       i_stereo_conf_threshold: 240
#       i_subpixel: true
#       i_threshold_filter_min_range: 300
#       i_threshold_filter_max_range: 10000
#       i_update_ros_base_time_on_ros_msg: false
#       i_width: 1040
#     use_sim_time: false
